spring:
  datasource:
    url: jdbc:mysql://localhost:3306/IMS_Dev?createDatabaseIfNotExist=true
    username: root
    password: poop
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
