spring:
  datasource:
    url: jdbc:mysql://localhost:1231/mysql?createDatabaseIfNotExist=true
    username: root
    password: 12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
